### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by sscotth** [jahnreektor/arkansas-saas-class#1]
I suggest folders for each lesson, with individual .rb files for each assignment in the lesson.  Are we going to write rspec tests as well?

**Comment by jahnreektor** [comment]
I want to try to go through it all.  I'd like to learn as much as over the next month as possible.  we should probably append our initials on our version of the hw.  E.g.  hw1-JR.rb or something.   I agree with your folder idea.

Nice buckethead pic.

**Comment by clakeb** [comment]
Fork and pull is my vote.

**Comment by jahnreektor** [comment]
Yeah, that makes sense.  I'm down for whatever!
