### ISSUE TITLE
Public or Private

### ISSUE THREAD

**Issue by sscotth** [jahnreektor/arkansas-saas-class#2]
Should this group be public?  I don't think we want the code searchable by the masses.  We can do the requests/invites in the meetup or facebook group.   

@jahnreektor Do you have private repo slots?

**Comment by jahnreektor** [comment]
Doesn't private cost money?

**Comment by clakeb** [comment]
I'll chip in for the repo if we need too. Are we having a little meeting after the meetup?

**Comment by jahnreektor** [comment]
Yeah, they won't be awarding the github accounts until a week after you turn the assignment 0 in.  (I never did it last time, but I did it this time.)

I don't think it really matters either way.  The class is free, so if someone searches for the code, they're only depriving themselves of the learning experience.    

Up to you guys, though.
